from src.core.tracks.models import Track


class TracksCrudDao:
    async def create(self, model: Track) -> bool: ...
    async def get(self, id: str) -> Track: ...
    async def read(self, skip: int = 0, limit: int = 100) -> list[Track]: ...
    async def find_by_name(self, name: str) -> list[Track]: ...
