from typing import Protocol
from .domains import Track


class TracksCrudPort(Protocol):
    def create(self, model: Track) -> bool: ...
    def get(self, id: int) -> Track: ...
    def read(self, skip: int = 0, limit: int = 100) -> list[Track]: ...
    def find_by_name(self, name: str) -> list[Track]: ...
