from typing import Protocol

from typing import Sequence

from src.generics.read_result import ReadDTO
from .domains import Track
from typing import Unpack
from .types import ReadTrackFilters


class TracksCrudPort(Protocol):
    async def create(self, model: Track) -> int|None: ...
    async def get(self, id: int) -> Track|None: ...
    async def read(
        self, skip: int = 0, limit: int = 100, **filters: Unpack[ReadTrackFilters]
    ) -> ReadDTO[Track] | None: ...

    async def get_hashs(self) -> Sequence[str]: ...

    async def get_random(self, n: int = 1) -> Sequence[Track]: ...

    async def search(self, query: str, limit: int = 100) -> Sequence[Track]: ...


class EmbeddingsCrudPort(Protocol):
    async def create(self, vector: list[float]) -> int | None: ...
    async def delete(self, id: int) -> bool: ...


class TracksStoragePort(Protocol):
    async def save(self, data: bytes) -> str: ...
    async def read(self, id: str) -> bytes: ...
    @staticmethod
    def is_safe_id(file_id: str) -> bool: ...
