from typing import Protocol
from .models import Track

class TracksCrudPort(Protocol):
    def create(self, model: Track) -> bool: ...
    def get(self, id: str) -> Track: ...
    def read(self, skip: int=0,limit: int = 100, **filters) -> list[Track]: ...
